# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("ISIN_check")
        MainWindow.resize(850, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 520))
        self.centralwidget.setObjectName("centralwidget")
        
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.addbutton = QtWidgets.QPushButton(self.centralwidget)
        self.addbutton.setObjectName("addbutton")
        self.addbutton.clicked.connect(self.addbutton_action)
        
        self.verticalLayout.addWidget(self.addbutton)
        
        self.addmultiplebutton = QtWidgets.QPushButton(self.centralwidget)
        self.addmultiplebutton.setObjectName("addmultiplebutton")
        self.addmultiplebutton.clicked.connect(self.addmultiplebutton_action)
        
        self.verticalLayout.addWidget(self.addmultiplebutton)
        
        self.editbutton = QtWidgets.QPushButton(self.centralwidget)
        self.editbutton.setObjectName("editbutton")
        self.editbutton.clicked.connect(self.editbutton_action)
        
        self.verticalLayout.addWidget(self.editbutton)
        
        self.deletebutton = QtWidgets.QPushButton(self.centralwidget)
        self.deletebutton.setObjectName("deletebutton")
        self.deletebutton.clicked.connect(self.deletebutton_action)#todo
        
        self.verticalLayout.addWidget(self.deletebutton)
        
        self.refreshbutton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshbutton.setObjectName("refreshbutton")
        self.refreshbutton.clicked.connect(self.refreshbutton_action)#todo
        
        self.verticalLayout.addWidget(self.refreshbutton)
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        
        self.verticalLayout.addWidget(self.label)
        
        self.sortbylist = QtWidgets.QListWidget(self.centralwidget)
        self.sortbylist.setObjectName("sortbylist")
        self.sortbylist.addItem("ISIN")
        self.sortbylist.addItem("WKN")
        self.sortbylist.addItem("Name")
        self.sortbylist.addItem("URL")
        self.sortbylist.addItem("Vola 1m")
        self.sortbylist.addItem("Vola 3m")
        self.sortbylist.addItem("Vola 1y")
        self.sortbylist.addItem("Vola 3y")
        self.sortbylist.addItem("Vola 5y")
        self.sortbylist.addItem("Vola 10y")
        self.sortbylist.addItem("Perf 1m")
        self.sortbylist.addItem("Perf 3m")
        self.sortbylist.addItem("Perf 1y")
        self.sortbylist.addItem("Perf 3y")
        self.sortbylist.addItem("Perf 5y")
        self.sortbylist.addItem("Perf 10y")
        self.sortbylist.addItem("Tag1")
        self.sortbylist.addItem("Tag2")
        self.sortbylist.addItem("Tag3")
        self.sortbylist.addItem("Last Update")
        self.sortbylist.itemClicked.connect(self.sortbylist_action)
        
        self.verticalLayout.addWidget(self.sortbylist)
        self.verticalLayout.setStretch(6, 1)
        
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.updateallbutton = QtWidgets.QPushButton(self.centralwidget)
        self.updateallbutton.setObjectName("updateallbutton")
        self.updateallbutton.clicked.connect(self.updateallbutton_action)
        
        self.horizontalLayout.addWidget(self.updateallbutton)
        
        self.updatebutton = QtWidgets.QPushButton(self.centralwidget)
        self.updatebutton.setObjectName("updatebutton")
        self.updatebutton.clicked.connect(self.updatebutton_action)
        
        self.horizontalLayout.addWidget(self.updatebutton)
        
        self.progress = QtWidgets.QProgressBar(self.centralwidget)
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        
        self.horizontalLayout.addWidget(self.progress)
        
        self.exportbutton = QtWidgets.QPushButton(self.centralwidget)
        self.exportbutton.setObjectName("exportbutton")
        self.exportbutton.clicked.connect(self.exportbutton_action)
        
        self.horizontalLayout.addWidget(self.exportbutton)
        
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        
        self.labelwarning = QtWidgets.QLabel(self.centralwidget)
        self.labelwarning.setObjectName("labelwarning")
        
        self.gridLayout_2.addWidget(self.labelwarning, 2, 0, 1, 1)
        
        self.copyright = QtWidgets.QLabel(self.centralwidget)
        self.copyright.setObjectName("copyright")
        self.copyright.setText('''<a href='https://github.com/JonathanFroe'>Jonathan Fröhlich</a>''')
        self.copyright.setOpenExternalLinks(True)
        
        self.gridLayout_2.addWidget(self.copyright, 2, 1, 1, 1)
        
        self.selected = QtWidgets.QLabel(self.centralwidget)
        self.selected.setObjectName("selected")
        
        self.gridLayout_2.addWidget(self.selected, 1, 1, 1, 1)
                
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(650, 400))
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.cellDoubleClicked.connect(self.onCellDoubleClicked)
        
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 22))
        self.menubar.setObjectName("menubar")
        
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        
        self.menuUpdate = QtWidgets.QMenu(self.menubar)
        self.menuUpdate.setObjectName("menuUpdate")
        
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        
        MainWindow.setStatusBar(self.statusbar)
                
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_as.triggered.connect(self.save_as_action)
        
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit.triggered.connect(self.close)
        
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionLoad.triggered.connect(self.load_action)
        
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionAdd.triggered.connect(self.addbutton_action)
        
        self.actionAdd_muliple = QtWidgets.QAction(MainWindow)
        self.actionAdd_muliple.setObjectName("actionAdd_muliple")
        self.actionAdd_muliple.triggered.connect(self.addmultiplebutton_action)
        
        self.actionUpdate_all = QtWidgets.QAction(MainWindow)
        self.actionUpdate_all.setObjectName("actionUpdate_all")
        self.actionUpdate_all.triggered.connect(self.updateallbutton_action)
        
        self.actionInfo_about_App = QtWidgets.QAction(MainWindow)
        self.actionInfo_about_App.setObjectName("actionInfo_about_App")
        self.actionInfo_about_App.triggered.connect(self.show_Info_action)
        
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        
        self.menuEdit.addAction(self.actionAdd)
        self.menuEdit.addAction(self.actionAdd_muliple)
        
        self.menuUpdate.addAction(self.actionUpdate_all)
        
        self.menuInfo.addAction(self.actionInfo_about_App)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuUpdate.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", self.filename))
        self.addbutton.setText(_translate("MainWindow", "Add"))
        self.addmultiplebutton.setText(_translate("MainWindow", "Add muliple"))
        self.editbutton.setText(_translate("MainWindow", "Edit Tag"))
        self.deletebutton.setText(_translate("MainWindow", "Delete"))
        self.refreshbutton.setText(_translate("MainWindow", "Refresh"))
        self.label.setText(_translate("MainWindow", "Sort by"))
        self.updateallbutton.setText(_translate("MainWindow", "Update all"))
        self.updatebutton.setText(_translate("MainWindow", "Update"))
        self.labelwarning.setText(_translate("MainWindow", "Please Click >Refresh< after each >Update< and >Add< to display the new values!"))
        self.exportbutton.setText(_translate("MainWindow", "Export"))
        self.selected.setText(_translate("MainWindow", "made with 🖤 by"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuUpdate.setTitle(_translate("MainWindow", "Update"))
        self.menuInfo.setTitle(_translate("MainWindow", "Info"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionLoad.setText(_translate("MainWindow", "Load/Create"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionAdd_muliple.setText(_translate("MainWindow", "Add muliple"))
        self.actionUpdate_all.setText(_translate("MainWindow", "Update all"))
        self.actionInfo_about_App.setText(_translate("MainWindow", "Info about App"))
